---
scene_name: "shape2_60deg"

# register_clouds params
scene_name: "register_clouds" # change this to config_name ?
register_clouds/source_file: "pcd_images/shape1_shape2/shape2_60deg_filtered.pcd"
register_clouds/target_file: "pcd_images/shape1_shape2/shape2.pcd"
register_clouds/aligned_file: "pcd_images/shape1_shape2/shape2_60deg_filtered_aligned.pcd"
part1_name: "shape2"
part1_type: "square_tube"
part2_name: "none"
part2_type: "none"
save_part1_segment: false
save_part2_segment: false
use_teaser: false
use_teaser_fpfh: false
wait_for_filter: false

register_clouds/filter_box: [0.0, 0.5, -0.9, -0.4, -0.01, 0.23] # bounding box limits (!check that these are used!)
register_clouds/voxel_leaf_size: 0.005                                         # voxel leaf size

icp_max_corr_dist: 1.0          # ICP Maximum Correspondence Distance
icp_max_iter: 1000                # ICP Maximum Iterations
icp_trns_epsl: 0.000000001        # ICP Transformation Epsilon
icp_ecld_fitn_epsl: 0.000000001  # ICP Euclidean Distance Fitness Epsilon          
icp_ran_rej_thrsh: 1.5           # ICP RANSAC Outlier Rejection Threshold 

expected_results: [0.1016, -0.6096, 0.0254,0.0,0.0,0.7854] # [4.0in, -24.0in, 1.0in]*(25.4e-3) #[0.0,0.0,45.0]*(pi/180)
calibration_offset: [-0.00893203,-0.000860624,0.00537355,-0.00493333,-0.000708936,0.019938]

