---
filter_cloud/input_file: "pcd_images/shape1_shape2/shape2_45deg.pcd"
filter_cloud/output_file: "pcd_images/shape1_shape2/shape2_45deg_filtered.pcd"
filter_cloud/target_file: "pcd_images/shape1_shape2/shape2.pcd"
save_output: true
translate_output: false
automatic_bounds: false
use_clustering: true

new_scan: false
transform_input: false

filter_cloud/pre_rotation:    [0.0, 0.0, 0.0]
filter_cloud/pre_translation: [0.0, 0.0, 0.0]

filter_cloud/filter_box: [-1.0, 1.0, -1.0, 0.0, 0.005, 0.5] # bounding box limits
filter_cloud/voxel_leaf_size: 0.001  