---
scene_name: "plate_rect_block_c1_30"
scene_file: "pcd_images/plate_rect_block/plate_rect_block_c1_30.pcd"
part1_name: "rect_block_02"
part1_file: "pcd_images/plate_rect_block/rect_block_02.pcd"
part1_type: "square_tube"
part2_name: "plate_02"
part2_type: "plate with notch"
seam1_length: 1.0

filter_params: [-0.25, 0.4, -0.25, 0.4, 0.00, 0.22, 0.0005]
ransac_params: [0.1,100,0.03]
icp_params: [1.0, 1000000000, 0.000000001, 0.000000001]

seam1_length: 1.0
seam1_xs: [10, 11, 12, 13]
seam1_ys: [20, 55, 22, 23]
seam1_zs: [30, 31, 54, 12]
