services:
  seam-detection:
    build: .
    #command: roslaunch seam_detection seam_detection.launch scene:="shape1_0deg"
    command: roslaunch seam_detection seam_detection.launch scene:="table_8in10in_tee_x4y24_45B"
    #command: roslaunch seam_detection seam_detection.launch scene:="plate_rect_block_02_dx100_rz30_blndr"
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $CATKIN_WS_PATH/src:/home/seamdetection_ws/src

  registration-examples: 
    build: .
    command: roslaunch seam_detection registration_examples.launch scene:="shape2_60deg"
    #command: roslaunch seam_detection registration_examples.launch scene:="table_8in10in_tee_x4y24_45_part1"
    #command: roslaunch seam_detection registration_examples.launch scene:="rect_block_02_blndr"
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $CATKIN_WS_PATH/src:/home/seamdetection_ws/src      

  cad-cloud: 
    build: .
    command: roslaunch seam_detection cad_cloud.launch n_samples:=1800 leaf_size:=.00025
             if:=$(find seam_detection)/ply_images/table_tee/8in10in_tee_01_blndr.ply
             of:=$(find seam_detection)/pcd_images/table_tee/8in10in_tee_01_blndr.pcd
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $CATKIN_WS_PATH/src:/home/seamdetection_ws/src

  cad-cloud-bulk: 
    build: .
    command: rosrun seam_detection cad_cloud_bulk -n_samples 4000 -leaf_size .00025 -write_normals 1 -input_dir "ply_images/shape1_shape2/" -output_dir "pcd_images/shape1_shape2/"
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $CATKIN_WS_PATH/src:/home/seamdetection_ws/src  

  filter-cloud: 
    build: .
    command: roslaunch seam_detection filter_cloud.launch filter_config:="shape1_90deg_filter"
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $CATKIN_WS_PATH/src:/home/seamdetection_ws/src    

  #bash: 
  #  build: .
  #  command: /bin/bash
  #  environment:
  #    DISPLAY: $DISPLA
  #  volumes:
  #    - /tmp/.X11-unix:/tmp/.X11-unix
  #    - ~/.Xauthority:/root/.Xauthority
  #    - $SD_PATH:/home/seamdetection_ws/src/seam_detection  

  #python-example: 
  #  build: .
  #  command: python3 example.py
  #  environment:
  #    DISPLAY: $DISPLAY
  #  volumes:
  #    - /tmp/.X11-unix:/tmp/.X11-unix
  #    - ~/.Xauthority:/root/.Xauthority
  #    - $SD_PATH:/home/seamdetection_ws/src/seam_detection      