services:
  seam-detection:
    build: .
    command: roslaunch seam_detection seam_detection.launch scene:="table_8in10in_tee_x4y24_45"

    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $CATKIN_WS_PATH/src:/home/seamdetection_ws/src

  registration-examples: 
    build: .
    command: roslaunch seam_detection registration_examples.launch scene:="rect_block_02_blndr"
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $CATKIN_WS_PATH/src:/home/seamdetection_ws/src      

  cad-cloud: 
    build: .
    command: roslaunch seam_detection cad_cloud.launch n_samples:=1800 leaf_size:=.00025
             if:=$(find seam_detection)/ply_images/table_tee/8in10in_tee_01_blndr.ply
             of:=$(find seam_detection)/pcd_images/table_tee/8in10in_tee_01_blndr.pcd
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $CATKIN_WS_PATH/src:/home/seamdetection_ws/src

    