---
# get_cloud params 
get_cloud/new_scan: false
get_cloud/output_file: "pcd_images/aubo_i10/aubo_cloud_out.pcd"
save_output: true
translate_output: false

# filter_cloud params
filter_cloud/input_file: "pcd_images/aubo_i10/aubo_cloud_out_10.pcd"
filter_cloud/output_file: "pcd_images/aubo_i10/aubo_cloud_out_filtered.pcd"
filter_cloud/target_file: "pcd_images/shape1_shape2/shape2.pcd"
save_output: true
translate_output: false
automatic_bounds: false
use_clustering: true

filter_cloud/filter_box: [-1.0, 1.0, -1.0, 0.0, 0.005, 0.5] # bounding box limits
filter_cloud/voxel_leaf_size: 0.001                           # voxel leaf size

# register_clouds params
scene_name: "aubo_i10_lidar" # change this to config_name ?
register_clouds/source_file: "pcd_images/aubo_i10/aubo_cloud_out_filtered.pcd"
register_clouds/target_file: "pcd_images/shape1_shape2/shape2.pcd"
register_clouds/aligned_file: "pcd_images/shape1_shape2/source_aligned.pcd"
part1_name: "shape1"
part1_type: "square_tube"
part2_name: "none"
part2_type: "none"
save_part1_segment: false
save_part2_segment: false
use_teaser: false
use_teaser_fpfh: false

register_cloud/filter_box: [0.0, 0.5, -0.9, -0.4, -0.01, 0.23] # bounding box limits (!check that these are used!)
register_cloud/voxel_leaf_size: 0.005                                         # voxel leaf size

icp_max_corr_dist: 1.0          # ICP Maximum Correspondence Distance
icp_max_iter: 1000                # ICP Maximum Iterations
icp_trns_epsl: 0.000000001        # ICP Transformation Epsilon
icp_ecld_fitn_epsl: 0.000000001  # ICP Euclidean Distance Fitness Epsilon          
icp_ran_rej_thrsh: 1.5           # ICP RANSAC Outlier Rejection Threshold           
