---
crg_segmentation/input_file: "pcd_images/ds435i_table_parts/table_part1_part2_02.pcd"
crg_segmentation/output_file: "pcd_images/ds435i_table_parts/table_part1_part2_02_crg.pcd"

save_output: true
translate_output: false
automatic_bounds: false
transform_input: true

crg_segmentation/pre_rotation:    [0.0, 3.14159, 0.0]
crg_segmentation/pre_translation: [0.0, 0.0, 0.8128] # 32.0*0.0254

crg_segmentation/filter_box: [-1.0, 1.0, -1.0, 1.0, 0.005, 0.5] # bounding box limits
crg_segmentation/voxel_leaf_size: 0.001                           # voxel leaf size
