---
input_dir: "pcd_images/PartNet/part1"
output_dir: "pcd_images/PartNet/part1/filtered"

save_output: true
translate_output: false
automatic_bounds: false
use_clustering: true
new_scan: false
transform_input: true

pre_rotation:    [-0.05, 3.17, 0.0] # ds435i rgb camera 32inches from table surface pointing down
pre_translation: [0.0, 0.0, 0.8128] # 32.0*0.0254 

bounding_box: [-0.5, 0.5, -0.5, 0.5, 0.0, 0.1] # bounding box limits
voxel_size: 0.002

