---
input_dir: "pcd_images/PartNet/floor_table_part1_ds455/all"
output_dir: "pcd_images/PartNet/floor_table_part1_ds455/all/filtered"

save_output: false
translate_output: false
automatic_bounds: false
use_clustering: true
new_scan: false
transform_input: true

pre_rotation:    [-0.05, 3.17, 0.0] # ds435i rgb camera 32inches from table surface pointing down
pre_translation: [0.0, 0.0, 0.8128] # 32.0*0.0254 

bounding_box: [-0.5, 0.4, -0.5, 0.3,  -0.25, 0.1] # bounding box limits
voxel_size: 0.005

