---
input_file: "pcd_images/shape3/shape3_60deg_2large.pcd"
output_file: "pcd_images/shape3/shape3_60deg_2large_filtered.pcd"
target_file: "pcd_images/shape1_shape2/shape1.pcd"
save_output: true
translate_output: false
automatic_bounds: false
use_clustering: true

filter_box: [-1.0, 1.0, -1.0, 0.0, 0.005, 0.5] # bounding box limits
voxel_leaf_size: 0.001                           # voxel leaf size
