---
scene_name: "aubo_i10_lidar"
source_file: "pcd_images/aubo_i10/aubo_cloud_out.pcd"
part1_name: "shape1"
target_file: "pcd_images/shape1_shape2/shape1.pcd"
part1_type: "unknown"
save_part1_segment: false
save_part2_segment: false
use_teaser: false
use_teaser_fpfh: false

#filter_box: [0.0, 0.5, -0.9, -0.4, -0.01, 0.23] # bounding box limits
#voxel_leaf_size: 0.005                           # voxel leaf size

#ransac_norm_dist_wt: 0.1 # RANSAC Normal Distance Weight
#ransac_max_iter: 100     # RANSAC Maximum Iterations
#ransac_dist_thrsh: 0.03  # RANSAC Distance Threshold
#ransac_k_srch: 50        # RANSAC KD Tree Parmeter(?)
#ransac_init_norm: [-1.0, 1.0, 0.0] # RANSAC init perpendicular vector

icp_max_corr_dist: 1.0          # ICP Maximum Correspondence Distance
icp_max_iter: 1000                # ICP Maximum Iterations
icp_trns_epsl: 0.000000001        # ICP Transformation Epsilon
icp_ecld_fitn_epsl: 0.000000001  # ICP Euclidean Distance Fitness Epsilon          
icp_ran_rej_thrsh: 1.5           # ICP RANSAC Outlier Rejection Threshold           