---
scene_name: "plate_round_tube_c2"
scene_file: "pcd_images/plate_round_tube/plate_round_tube_c2.pcd"
part1_name: "round_tube_01"
part1_file: "pcd_images/plate_round_tube/round_tube_01.pcd"
part1_type: "round_tube"
part2_name: "plate"
part2_type: "plate with notch"
seam1_length: 1.0
seam1_points:
  - 0.1
  - 0.2
  - 0.3
