---
scene_name: "plate_square_tube_c2"
scene_file: "pcd_images/plate_square_tube/plate_square_tube_c2.pcd"
part1_name: "square_tube_01"
part1_file: "pcd_images/plate_square_tube/square_tube_01.pcd"
part1_type: "square_tube"
part2_name: "plate"
part2_type: "plate with notch"
seam1_length: 1.0
seam1_points:
  - 0.1
  - 0.2
  - 0.3
