---
scene_name: "plate_round_cylinder_c1"
scene_file: "pcd_images/plate_round_cylinder/plate_round_cylinder_c1.pcd"
part1_name: "round_cylinder_01"
part1_file: "pcd_images/plate_round_cylinder/round_cylinder_01.pcd"
part1_type: "round_tube"
part2_name: "plate"
part2_type: "plate with notch"
seam1_length: 1.0

seam1_xs: [10, 11, 12, 13]
seam1_ys: [20, 21, 22, 23]
seam1_zs: [30, 31, 32, 33]

icp_params: [1.0, 100000, 0.000001, 0.000001]
