---
scene_name: "plate_rect_block_02_dx100_rz30_blndr"
lidar_src_file: "pcd_images/plate_rect_block/plate_rect_block_02_dx100_rz30_blndr.pcd"
part1_name: "rect_block_02"
cad_ref_file: "pcd_images/plate_rect_block/rect_block_02_blndr.pcd"
part1_type: "square_tube"
part2_name: "plate_02"
part2_type: "plate with notch"

filter_box: [-0.15, 0.20, -0.15, 0.2, 0.00, 0.22, 0.0005] # bounding box limits
voxel_leaf_size: 0.0005                           # voxel leaf size

ransac_norm_dist_wt: 0.1 # RANSAC Normal Distance Weight
ransac_max_iter: 100     # RANSAC Maximum Iterations
ransac_dist_thrsh: 0.03  # RANSAC Distance Threshold
ransac_k_srch: 50        # RANSAC KD Tree Parmeter(?)
ransac_init_norm: [0.0, 1.0, 0.0] # RANSAC init perpendiculr vector

icp_max_corr_dist: 0.5            # ICP Maximum Correspondence Distance
icp_max_iter: 1000000000          # ICP Maximum Iterations
icp_trns_epsl: 0.000000001        # ICP Transformation Epsilon
icp_ecld_fitn_epsl: 0.000000001   # ICP Euclidean Distance Fitness Epsilon          

expected_results: [0.200, 0.250, 0.025,0.0,0.0,0.5236] # [4.0in, -24.0in, 1.0in]*(25.4e-3) #[0.0,0.0,45.0]*(pi/180)
calibration_offset: [0.0, 0.0, 0.0,0.0,0.0,0.0]

seam1_length: 1.0                      # weld seam length
seam1_points_x: [10, 11, 12, 13]       # weld seam control points
seam1_points_y: [20, 55, 22, 23]
seam1_points_z: [30, 31, 54, 12]