---
scene_name: "plate_square_tube_c0"
scene_file: "pcd_images/plate_square_tube/plate_square_tube_c0.pcd"
part1_name: "square_tube_01"
part1_file: "pcd_images/plate_square_tube/square_tube_01.pcd"
part1_type: "square_tube"
part2_name: "plate_02"
part2_type: "plate with notch"
seam1_length: 1.0

seam1_xs: [10, 11, 12, 13]
seam1_ys: [20, 21, 22, 23]
seam1_zs: [30, 31, 32, 33]


#seam1_points:
#    -   - 12
#        - 43
#        - 74
#    -   - 34
#        - 203
#        - 1
#...
