---
scene_name: "plate_rect_block_c1"
scene_file: "pcd_images/plate_rect_block/plate_rect_block_c1.pcd"
part1_name: "rect_block_02"
part1_file: "pcd_images/plate_rect_block/rect_block_02.pcd"
part1_type: "generic"
part2_name: "none"
part2_type: "none"
seam1_length: 1.0

seam1_xs: [10, 11, 12, 13]
seam1_ys: [20, 21, 22, 23]
seam1_zs: [30, 31, 32, 33]

icp_params: [1.0, 100000, 0.000001, 0.000001]
