
# register_clouds params
scene_name: "register_clouds" # change this to config_name ?
#register_clouds/source_file: "pcd_images/shape1_shape2/shape1_0deg_filtered.pcd"
#register_clouds/target_file: "pcd_images/shape1_shape2/shape1.pcd"
#register_clouds/aligned_file: "pcd_images/aubo_i10/aubo_source_aligned.pcd"

#register_clouds/source_file: "bags/reconstruction/part1_x4_y9_theta0_output.pcd"
#register_clouds/source_file: "bags/reconstruction/part1_x9_y7_theta90_output.pcd"
#register_clouds/source_file: "bags/reconstruction/part1_x3_y9_theta0_output.pcd"
#register_clouds/source_file: "bags/reconstruction/part1_x9_y7_theta90_output.pcd"
register_clouds/source_file: "bags/reconstruction/part1_x3_y9_theta0_5_output.pcd"

#register_clouds/target_file: "bags/reconstruction/part1_x5_y10_theta45_output.pcd"
#register_clouds/target_file: "bags/reconstruction/part1_x7_y5_theta45_output.pcd"
#register_clouds/target_file: "bags/reconstruction/part1_x9_y7_theta90_output.pcd"
register_clouds/target_file: "bags/reconstruction/part1_x7_y5_theta45_5_output.pcd"

register_clouds/aligned_file: "bags/reconstruction/part1_aligned.pcd"

part1_name: "shape1"
part1_type: "square_tube"
part2_name: "none"
part2_type: "none"
save_part1_segment: false
save_part2_segment: false

use_icp: true
use_teaser: false
use_teaser_fpfh: false

wait_for_filter: false

register_clouds/filter_box: [0.0, 0.5, -0.9, -0.4, -0.01, 0.23] # bounding box limits (!check that these are used!)
register_clouds/voxel_leaf_size: 0.005                                         # voxel leaf size

icp_max_corr_dist: 1.0          # ICP Maximum Correspondence Distance
icp_max_iter: 1000                # ICP Maximum Iterations
icp_trns_epsl: 0.000000001        # ICP Transformation Epsilon
icp_ecld_fitn_epsl: 0.000000001  # ICP Euclidean Distance Fitness Epsilon          
icp_ran_rej_thrsh: 1.5           # ICP RANSAC Outlier Rejection Threshold           
