---
# teach_points params
teach_points/num_points: 3

# get_target params 
get_target/new_scan: true
get_target/output_file: "pcd_images/aubo_i10/aubo_target_out.pcd"
save_output: true
translate_output: false

# filter_target params
filter_target/input_file: "pcd_images/aubo_i10/aubo_target_out.pcd"
filter_target/output_file: "pcd_images/aubo_i10/aubo_target_out_filtered.pcd"
filter_target/target_file: "pcd_images/shape1_shape2/shape2.pcd"
save_output: true
translate_output: false
automatic_bounds: false
use_clustering: true
filter_target/filter_box: [-1.0, 1.0, -1.0, 0.0, 0.002, 0.5] # bounding box limits
filter_target/voxel_leaf_size: 0.001                           # voxel leaf size

# get_source params 
get_source/new_scan: true
get_source/output_file: "pcd_images/aubo_i10/aubo_source_out.pcd"
save_output: true
translate_output: false

# filter_source params
filter_source/input_file: "pcd_images/aubo_i10/aubo_source_out.pcd"
filter_source/output_file: "pcd_images/aubo_i10/aubo_source_out_filtered.pcd"
filter_source/target_file: "pcd_images/shape1_shape2/shape2.pcd"
save_output: true
translate_output: false
automatic_bounds: false
use_clustering: true
filter_source/filter_box: [-1.0, 1.0, -1.0, 0.0, 0.002, 0.5] # bounding box limits
filter_source/voxel_leaf_size: 0.001   

# register_target_source params
scene_name: "aubo_i10_lidar" # change this to config_name ?
#register_target_source/source_file: "pcd_images/aubo_i10/aubo_source_out_filtered.pcd"
#register_target_source/target_file: "pcd_images/aubo_i10/aubo_target_out_filtered.pcd"
#register_target_source/aligned_file: "pcd_images/aubo_i10/aubo_source_aligned.pcd"
register_target_source/source_file: "bags/reconstruction/demo_part1_clutter_2_output.pcd"
register_target_source/target_file: "bags/reconstruction/demo_part1_2_output.pcd"
register_target_source/aligned_file: "bags/reconstruction/demo_part1_2_output.pcd"
part1_name: "shape1"
part1_type: "square_tube"
part2_name: "none"
part2_type: "none"
save_part1_segment: false
save_part2_segment: false
use_teaser: false
use_teaser_fpfh: false

register_target_source/filter_box: [0.0, 0.5, -0.9, -0.4, -0.01, 0.23] # bounding box limits (!check that these are used!)
register_target_source/voxel_leaf_size: 0.005                                         # voxel leaf size

icp_max_corr_dist: 1.0          # ICP Maximum Correspondence Distance
icp_max_iter: 1000                # ICP Maximum Iterations
icp_trns_epsl: 0.000000001        # ICP Transformation Epsilon
icp_ecld_fitn_epsl: 0.000000001  # ICP Euclidean Distance Fitness Epsilon          
icp_ran_rej_thrsh: 1.5           # ICP RANSAC Outlier Rejection Threshold           
