---

input_file: "pcd_images/shape1_shape2/shape2_90deg.pcd"
output_file: "pcd_images/shape1_shape2/shape2_90deg_filtered.pcd"
save_output: true

translate_output: true # re-center the cloud about the corner of the bounding box

filter_box: [-0.5, 0.5, -1.0, -0.25, 0.005, 0.25] # bounding box limits

voxel_leaf_size: 0.001                           # voxel leaf size
