---
scene_name: "shape2_60deg"
source_file: "pcd_images/shape1_shape2/shape2_60deg_filtered.pcd"
part1_name: "shape1"
target_file: "pcd_images/shape1_shape2/shape2.pcd"
aligned_file: "pcd_images/shape1_shape2/shape2_60deg_filtered_aligned.pcd"
part1_type: "square_tube"
part2_name: "none"
part2_type: "none"
save_part1_segment: false
save_part2_segment: false

use_teaser: false
use_teaser_fpfh: false
save_aligned: true

filter_box: [0.0, 0.5, -0.9, -0.4, -0.01, 0.23] # bounding box limits
#filter_box: [-1.0, 1.0, -1.0, 1.0, -1.0, 1.0] # bounding box limits

voxel_leaf_size: 0.005                           # voxel leaf size

ransac_norm_dist_wt: 0.1 # RANSAC Normal Distance Weight
ransac_max_iter: 100     # RANSAC Maximum Iterations
ransac_dist_thrsh: 0.03  # RANSAC Distance Threshold
ransac_k_srch: 50        # RANSAC KD Tree Parmeter(?)
ransac_init_norm: [-1.0, 1.0, 0.0] # RANSAC init perpendiculr vector

icp_max_corr_dist: 0.5            # ICP Maximum Correspondence Distance
icp_max_iter: 1000         # ICP Maximum Iterations
icp_trns_epsl: 0.000000001        # ICP Transformation Epsilon
icp_ecld_fitn_epsl: 0.000000001  # ICP Euclidean Distance Fitness Epsilon          
icp_ran_rej_thrsh: 1.5           # ICP RANSAC Outlier Rejection Threshold          

expected_results: [0.1016, -0.6096, 0.0254,0.0,0.0,0.7854] # [4.0in, -24.0in, 1.0in]*(25.4e-3) #[0.0,0.0,45.0]*(pi/180)
calibration_offset: [-0.00893203,-0.000860624,0.00537355,-0.00493333,-0.000708936,0.019938]

seam1_length: 1.0                      # weld seam length
seam1_points_x: [10, 11, 12, 13]       # weld seam control points
seam1_points_y: [20, 55, 22, 23]
seam1_points_z: [30, 31, 54, 12]