---
scene_name: "table_tee_c1"
scene_file: "pcd_images/table_tee/table_tee_c1.pcd"
part1_name: "tee_01"
part1_file: "pcd_images/table_tee/tee_01.pcd"
part1_type: "generic"
part2_name: "none"
part2_type: "none"
seam1_length: 1.0

seam1_xs: [10, 11, 12, 13]
seam1_ys: [20, 21, 22, 23]
seam1_zs: [30, 31, 32, 33]

icp_params: [1.0, 1000000, 0.0000001, 0.0000001]
